const DEFAULT_SUPPLY_NODES = [
  {
    nodeId: 'n-shanghai-port',
    name: 'Shanghai Port',
    type: 'port',
    location: 'Shanghai, China',
    region: 'Asia',
    status: 'active',
    capacityUnits: 9200,
    utilizationRate: 0.78,
    riskScore: 0.34,
    x: 638,
    y: 152,
  },
  {
    nodeId: 'n-shenzhen-supplier',
    name: 'Shenzhen Electronics Supplier',
    type: 'supplier',
    location: 'Shenzhen, China',
    region: 'Asia',
    status: 'active',
    capacityUnits: 5100,
    utilizationRate: 0.71,
    riskScore: 0.29,
    x: 608,
    y: 182,
  },
  {
    nodeId: 'n-hochiminh-supplier',
    name: 'Ho Chi Minh Component Supplier',
    type: 'supplier',
    location: 'Ho Chi Minh City, Vietnam',
    region: 'Asia',
    status: 'active',
    capacityUnits: 3900,
    utilizationRate: 0.66,
    riskScore: 0.25,
    x: 585,
    y: 218,
  },
  {
    nodeId: 'n-shanghai-warehouse',
    name: 'Shanghai Consolidation Warehouse',
    type: 'warehouse',
    location: 'Shanghai, China',
    region: 'Asia',
    status: 'active',
    capacityUnits: 6400,
    utilizationRate: 0.62,
    riskScore: 0.22,
    x: 620,
    y: 168,
  },
  {
    nodeId: 'n-rotterdam-port',
    name: 'Rotterdam Port',
    type: 'port',
    location: 'Rotterdam, Netherlands',
    region: 'Europe',
    status: 'active',
    capacityUnits: 7300,
    utilizationRate: 0.58,
    riskScore: 0.18,
    x: 318,
    y: 92,
  },
  {
    nodeId: 'n-eu-dc',
    name: 'EU Distribution Center',
    type: 'warehouse',
    location: 'Eindhoven, Netherlands',
    region: 'Europe',
    status: 'active',
    capacityUnits: 4200,
    utilizationRate: 0.54,
    riskScore: 0.16,
    x: 335,
    y: 105,
  },
  {
    nodeId: 'n-us-west-dc',
    name: 'US West Distribution Center',
    type: 'warehouse',
    location: 'Los Angeles, USA',
    region: 'North America',
    status: 'active',
    capacityUnits: 7000,
    utilizationRate: 0.74,
    riskScore: 0.21,
    x: 98,
    y: 162,
  },
];

const DEFAULT_SUPPLY_ROUTES = [
  {
    routeId: 'r-shanghai-to-rotterdam-ocean',
    fromNodeId: 'n-shanghai-port',
    toNodeId: 'n-rotterdam-port',
    mode: 'ocean',
    status: 'active',
    weeklyCapacityTeu: 1650,
    avgTransitDays: 29,
    delayDays: 0,
    riskScore: 0.27,
    flowPercent: 0.28,
  },
  {
    routeId: 'r-shanghai-to-usw-ocean',
    fromNodeId: 'n-shanghai-port',
    toNodeId: 'n-us-west-dc',
    mode: 'ocean',
    status: 'active',
    weeklyCapacityTeu: 2100,
    avgTransitDays: 21,
    delayDays: 0,
    riskScore: 0.31,
    flowPercent: 0.34,
  },
  {
    routeId: 'r-supplier-to-shanghai-wh-truck',
    fromNodeId: 'n-shenzhen-supplier',
    toNodeId: 'n-shanghai-warehouse',
    mode: 'truck',
    status: 'active',
    weeklyCapacityTeu: 720,
    avgTransitDays: 3,
    delayDays: 0,
    riskScore: 0.19,
    flowPercent: 0.11,
  },
  {
    routeId: 'r-vietnam-to-shanghai-ocean',
    fromNodeId: 'n-hochiminh-supplier',
    toNodeId: 'n-shanghai-port',
    mode: 'ocean',
    status: 'active',
    weeklyCapacityTeu: 850,
    avgTransitDays: 6,
    delayDays: 0,
    riskScore: 0.22,
    flowPercent: 0.09,
  },
  {
    routeId: 'r-rotterdam-to-eudc-rail',
    fromNodeId: 'n-rotterdam-port',
    toNodeId: 'n-eu-dc',
    mode: 'rail',
    status: 'active',
    weeklyCapacityTeu: 760,
    avgTransitDays: 2,
    delayDays: 0,
    riskScore: 0.14,
    flowPercent: 0.08,
  },
  {
    routeId: 'r-shanghai-to-usw-air',
    fromNodeId: 'n-shanghai-port',
    toNodeId: 'n-us-west-dc',
    mode: 'air',
    status: 'active',
    weeklyCapacityTeu: 160,
    avgTransitDays: 2,
    delayDays: 0,
    riskScore: 0.12,
    flowPercent: 0.1,
  },
];

module.exports = { DEFAULT_SUPPLY_NODES, DEFAULT_SUPPLY_ROUTES };
